version: "3"
services:
  proxy:
    hostname: proxy
    image: jwilder/nginx-proxy
    container_name: proxydaw
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy:/etc/nginx/vhost.d:ro
      - "./conf/my_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf:ro"
    networks:
      - frontend
  db:
    hostname: db
    image: mysql:5.7
    container_name: dbdaw
    volumes:
      - ./data/db:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    networks:
      - backend
  mvc:
    build: ./dockerfiles/mvc
    container_name: mvc
    hostname: mvc
    volumes:
      - ./data/mvc:/var/www/html
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=mvc.local,www.mvc.local
    restart: always
    networks:
      - frontend
      - backend
  laravel:
    build:
      context: './laravel'
      args:
        uid: ${UID}
    container_name: laravel
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
      - VIRTUAL_HOST=laravel.local
    volumes:
      - ./data/laravel:/var/www/html
    networks:
      - frontend
      - backend
  laravel9:
    build:
      context: './laravel9'
      args:
        uid: ${UID}
    container_name: laravel9
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
      - VIRTUAL_HOST=laravel9.local
    volumes:
      - ./data/laravel9:/var/www/html
    networks:
      - frontend
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
      - PMA_HOST=db
      - VIRTUAL_HOST=phpmyadmin.docker
    networks:
      - frontend
      - backend
networks:
  frontend:
  backend:
